import os
import json
import glob
import requests
import sys

def main():
    reports_dir = os.environ.get('REPORTS_DIR', 'reports')
    ollama_url = os.environ.get('OLLAMA_URL', 'http://172.17.0.11:11434/api/generate')
    llm_model = os.environ.get('LLM_MODEL', 'qwen2.5-coder:7b')
    
    print(f"[*] Starting AI Security Review using model {llm_model} at {ollama_url}")
    print(f"[*] Reading reports from {reports_dir}...")
    
    # Read all JSON reports
    json_files = glob.glob(os.path.join(reports_dir, '*.json'))
    if not json_files:
        print("[!] No JSON reports found in the reports directory.")
        sys.exit(0)
        
    combined_reports = {}
    for filepath in json_files:
        filename = os.path.basename(filepath)
        try:
            with open(filepath, 'r') as f:
                data = json.load(f)
                combined_reports[filename] = data
        except Exception as e:
            print(f"[!] Error reading {filename}: {e}")
            
    if not combined_reports:
        print("[!] No valid JSON data extracted from reports.")
        sys.exit(0)
        
    # Build prompt
    prompt = f"""
You are an expert DevSecOps and FinOps engineer.
Please review the following security and code quality reports generated by our CI pipeline scanners (like SonarQube, checkov, tfsec, etc.).

Reports data:
{json.dumps(combined_reports, indent=2)[:4000]} # Truncating to 4000 chars to avoid overwhelming the context window, though Qwen handles much more.

Please provide:
1. A brief summary of the most critical security vulnerabilities found.
2. Actionable recommendations on how to fix them.
3. Any best practices that are being violated.

Format your response in Markdown. Keep it concise but comprehensive.
"""

    print("[*] Sending data to LLM...")
    
    payload = {
        "model": llm_model,
        "prompt": prompt,
        "stream": False
    }
    
    try:
        response = requests.post(ollama_url, json=payload, timeout=120)
        response.raise_for_status()
        result = response.json()
        
        print("\n" + "="*50)
        print("🤖 AI SECURITY RECOMMENDATIONS")
        print("="*50 + "\n")
        
        print(result.get('response', 'No response field found in the API output.'))
        
        print("\n" + "="*50 + "\n")
        
    except requests.exceptions.RequestException as e:
        print(f"[!] Failed to connect to Ollama API: {e}")
        print("[!] Please ensure the Ollama container is running and accessible from the Jenkins agent.")
        sys.exit(1)

if __name__ == "__main__":
    main()
